// Writes src/version.ts from package.json so the version is compiled in
// (standalone binaries have no package.json next to them).
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const out = `// Generated by scripts/gen-version.mjs; do not edit.\nexport const VERSION = '${version}';\n`;
const path = new URL('../src/version.ts', import.meta.url);
let current = '';
try {
  current = readFileSync(path, 'utf8');
} catch {}
if (current !== out) writeFileSync(path, out);

// Keep the Claude Code plugin, MCP Registry entry and Gemini CLI extension on the package version
for (const file of ['../.claude-plugin/plugin.json', '../server.json', '../gemini-extension.json']) {
  const url = new URL(file, import.meta.url);
  const text = readFileSync(url, 'utf8');
  const json = JSON.parse(text);
  json.version = version;
  for (const pkg of json.packages ?? []) pkg.version = version;
  const next = JSON.stringify(json, null, 2) + '\n';
  if (next !== text) writeFileSync(url, next);
}

// Embed the agent skill so `telegram skill install` works from brew and standalone binaries too
const skillDir = new URL('../skills/better-tg-cli/', import.meta.url);
const skillFiles = Object.fromEntries(['SKILL.md', 'reference.md'].map(f => [f, readFileSync(new URL(f, skillDir), 'utf8')]));
const skillOut = `// Generated by scripts/gen-version.mjs from skills/better-tg-cli; do not edit.\nexport const SKILL_FILES: Record<string, string> = ${JSON.stringify(skillFiles, null, 2)};\n`;
const skillPath = new URL('../src/skill-files.ts', import.meta.url);
let skillCurrent = '';
try {
  skillCurrent = readFileSync(skillPath, 'utf8');
} catch {}
if (skillCurrent !== skillOut) writeFileSync(skillPath, skillOut);

// plugin/ is the folder submitted to Anthropic's plugin directory: regular files only (no links
// into the repo), the MCP server pinned to this exact version, the skill and LICENSE copied in
{
  const root = JSON.parse(readFileSync(new URL('../.claude-plugin/plugin.json', import.meta.url), 'utf8'));
  root.mcpServers.telegram.args = ['-y', `better-tg-cli@${version}`, 'mcp'];
  // Unofficial client: no brand name in the display name
  root.displayName = 'better-tg-cli';
  root.description = 'Unofficial Telegram client for your own account: a skill for the telegram CLI plus a local MCP server to read, search and send messages. Writes stay off until you allow them.';
  const files = {
    '.claude-plugin/plugin.json': JSON.stringify(root, null, 2) + '\n',
    'LICENSE': readFileSync(new URL('../LICENSE', import.meta.url), 'utf8'),
    // The directory wants a square icon of at least 128px
    '.claude-plugin/icon.svg': readFileSync(new URL('../assets/icon.svg', import.meta.url), 'utf8').replace('width="120" height="120"', 'width="512" height="512"'),
    ...Object.fromEntries(Object.entries(skillFiles).map(([f, c]) => [`skills/better-tg-cli/${f}`, c])),
    // ...and the Codex / ChatGPT plugin (repo marketplace in .agents/plugins/marketplace.json).
    // The MCP config stays out of the plugin root, where Claude Code would load it a second time
    '.codex-plugin/plugin.json': JSON.stringify({
      name: root.name,
      version,
      description: root.description,
      author: root.author,
      homepage: root.homepage,
      repository: root.repository,
      license: root.license,
      keywords: root.keywords,
      skills: './skills/',
      mcpServers: './.codex-plugin/mcp.json',
      interface: { displayName: root.displayName },
    }, null, 2) + '\n',
    '.codex-plugin/mcp.json': JSON.stringify({ mcpServers: root.mcpServers }, null, 2) + '\n',
    // The same folder is the Cursor Marketplace plugin (Cursor reads .cursor-plugin/plugin.json)
    '.cursor-plugin/plugin.json': JSON.stringify({
      name: root.name,
      displayName: root.displayName,
      description: root.description,
      version,
      author: root.author,
      homepage: root.homepage,
      repository: root.repository,
      license: root.license,
      keywords: root.keywords,
      logo: 'https://raw.githubusercontent.com/TheVilfer/better-tg-cli/main/assets/icon-512.png',
      mcpServers: root.mcpServers,
    }, null, 2) + '\n',
  };
  const { mkdirSync } = await import('node:fs');
  for (const [file, content] of Object.entries(files)) {
    const url = new URL(`../plugin/${file}`, import.meta.url);
    mkdirSync(new URL('.', url), { recursive: true });
    let cur = '';
    try { cur = readFileSync(url, 'utf8'); } catch {}
    if (cur !== content) writeFileSync(url, content);
  }
}
