#!/usr/bin/env node
// Print the Homebrew formula for a release from its SHA256SUMS file.
// Usage: node scripts/homebrew-formula.mjs <version> <SHA256SUMS path>
import { readFileSync } from 'node:fs';

const [version, sumsPath] = process.argv.slice(2);
if (!version || !sumsPath) {
  console.error('Usage: homebrew-formula.mjs <version> <SHA256SUMS>');
  process.exit(1);
}

const sums = Object.fromEntries(
  readFileSync(sumsPath, 'utf8')
    .trim()
    .split('\n')
    .map(line => line.trim().split(/\s+/))
    .map(([sha, file]) => [file.replace(/^\*/, ''), sha])
);
const asset = target => {
  const file = `better-tg-cli-${version}-${target}.tar.xz`;
  if (!sums[file]) throw new Error(`No checksum for ${file}`);
  return `url "https://github.com/TheVilfer/better-tg-cli/releases/download/v${version}/${file}"\n      sha256 "${sums[file]}"`;
};

process.stdout.write(`# Generated by better-tg-cli's release workflow; do not edit by hand.
class BetterTgCli < Formula
  desc "Unofficial agent-friendly Telegram client for the command line"
  homepage "https://github.com/TheVilfer/better-tg-cli"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      ${asset('darwin-arm64')}
    end
    on_intel do
      ${asset('darwin-x64')}
    end
  end

  on_linux do
    on_arm do
      ${asset('linux-arm64')}
    end
    on_intel do
      ${asset('linux-x64')}
    end
  end

  def install
    bin.install "telegram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/telegram --version")
    assert_match "read <chat>", shell_output("#{bin}/telegram help-all -g thread")
  end
end
`);
